// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW1ByIIdg-qBOqlRL3vukwUxwJumGiJJY',
    appId: '1:177458783886:web:52dab497f4818d76c00bdf',
    messagingSenderId: '177458783886',
    projectId: 'proyek3-d615c',
    authDomain: 'proyek3-d615c.firebaseapp.com',
    storageBucket: 'proyek3-d615c.appspot.com',
    measurementId: 'G-ND0TRVKY91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH99Wzfj2B7LwQF_zVGRuGm3w3DULq0hk',
    appId: '1:177458783886:android:ca4e2192bb8c3086c00bdf',
    messagingSenderId: '177458783886',
    projectId: 'proyek3-d615c',
    storageBucket: 'proyek3-d615c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8BP9Ex1MJue-vMazAv8KM8TY4TM9K5r8',
    appId: '1:177458783886:ios:589dc427e56c0848c00bdf',
    messagingSenderId: '177458783886',
    projectId: 'proyek3-d615c',
    storageBucket: 'proyek3-d615c.appspot.com',
    iosClientId: '177458783886-n123d5lnsto08tn7ke8p3292t8fknijq.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiMobile',
  );
}
